---
all:
  vars:
    ansible_connection: ssh
    connection: local
    # ansible_user: ec2-user
    # ansible_become: true
    # ansible_ssh_private_key_file: /tmp/certs/ssh_priv.pem

terraform_vault_demo:
  hosts:
    localhost: